/**
 * The Things Network Data Storage
 * Stores data and makes it available using a REST API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@thethingsindustries.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Data', 'api/DevicesApi', 'api/QueryApi', 'api/QuerydeviceIdApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Data'), require('./api/DevicesApi'), require('./api/QueryApi'), require('./api/QuerydeviceIdApi'));
  }
}(function(ApiClient, Data, DevicesApi, QueryApi, QuerydeviceIdApi) {
  'use strict';

  /**
   * Stores_data_and_makes_it_available_using_a_REST_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var TheThingsNetworkDataStorage = require('index'); // See note below*.
   * var xxxSvc = new TheThingsNetworkDataStorage.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new TheThingsNetworkDataStorage.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new TheThingsNetworkDataStorage.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new TheThingsNetworkDataStorage.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 2.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Data model constructor.
     * @property {module:model/Data}
     */
    Data: Data,
    /**
     * The DevicesApi service constructor.
     * @property {module:api/DevicesApi}
     */
    DevicesApi: DevicesApi,
    /**
     * The QueryApi service constructor.
     * @property {module:api/QueryApi}
     */
    QueryApi: QueryApi,
    /**
     * The QuerydeviceIdApi service constructor.
     * @property {module:api/QuerydeviceIdApi}
     */
    QuerydeviceIdApi: QuerydeviceIdApi
  };

  return exports;
}));
