/**
 * The Things Network Data Storage
 * Stores data and makes it available using a REST API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@thethingsindustries.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ttnapi/ApiClient', 'ttnapi/model/Data'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Data'));
  } else {
    // Browser globals (root is window)
    if (!root.TheThingsNetworkDataStorage) {
      root.TheThingsNetworkDataStorage = {};
    }
    root.TheThingsNetworkDataStorage.QuerydeviceIdApi = factory(root.TheThingsNetworkDataStorage.ApiClient, root.TheThingsNetworkDataStorage.Data);
  }
}(this, function(ApiClient, Data) {
  'use strict';

  /**
   * QuerydeviceId service.
   * @module api/QuerydeviceIdApi
   * @version 2.0.0
   */

  /**
   * Constructs a new QuerydeviceIdApi. 
   * @alias module:api/QuerydeviceIdApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the apiV2QueryDeviceIdGet operation.
     * @callback module:api/QuerydeviceIdApi~apiV2QueryDeviceIdGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Data>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Query data for a specific device
     * Query the data for a specific device 
     * @param {String} deviceId The ID of the device for which we want to get the data 
     * @param {Object} opts Optional parameters
     * @param {String} opts.last Duration on which we want to get the data (default 1h). Pass 30s for the last 30 seconds, 1h for the last hour, 2d for the last 48 hours, etc 
     * @param {module:api/QuerydeviceIdApi~apiV2QueryDeviceIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Data>}
     */
    this.apiV2QueryDeviceIdGet = function(deviceId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'deviceId' is set
      if (deviceId === undefined || deviceId === null) {
        throw new Error("Missing the required parameter 'deviceId' when calling apiV2QueryDeviceIdGet");
      }


      var pathParams = {
        'device-id': deviceId
      };
      var queryParams = {
        'last': opts['last'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Data];

      return this.apiClient.callApi(
        '/api/v2/query/{device-id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
